model_list:
  - model_name: glm-5-turbo
    litellm_params:
      model: openai/glm-5-turbo
      api_base: https://api.z.ai/api/coding/paas/v4
      api_key: os.environ/ZAI_API_KEY

  - model_name: code
    litellm_params:
      model: anthropic/glm-5-turbo
      api_base: https://api.z.ai/api/anthropic
      api_key: os.environ/ZAI_API_KEY

  - model_name: pencil
    litellm_params:
      model: anthropic/mimo-v2-omni
      api_base: https://api.xiaomimimo.com/anthropic
      api_key: os.environ/XIAOMI_API_KEY

  - model_name: kimi-k2.5
    litellm_params:
      model: anthropic/kimi-k2.5
      api_base: https://api.moonshot.ai/anthropic
      api_key: os.environ/MOONSHOT_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: "postgresql://postgres:postgres@host.docker.internal:5432/litellm"

litellm_settings:
  num_retries: 1
  allowed_fails: 1
  cooldown_time: 3600

router_settings:
  fallbacks:
    - code: ["kimi-k2.5"]
