model_list:
  # openai
  - model_name: zai/glm-5.1
    litellm_params:
      model: openai/glm-5.1
      api_base: https://api.z.ai/api/coding/paas/v4
      api_key: os.environ/ZAI_API_KEY

  - model_name: moonshot/kimi-2.5
    litellm_params:
      model: openai/kimi-k2.5
      api_base: https://api.moonshot.ai/v1
      api_key: os.environ/MOONSHOT_API_KEY

  # anthropic
  - model_name: zai/glm-5.1/a
    litellm_params:
      model: anthropic/glm-5.1
      api_base: https://api.z.ai/api/anthropic
      api_key: os.environ/ZAI_API_KEY

  - model_name: xiaomi/mimo-v2-omni/a
    litellm_params:
      model: anthropic/mimo-v2-omni
      api_base: https://api.xiaomimimo.com/anthropic
      api_key: os.environ/XIAOMI_API_KEY

  - model_name: moonshot/kimi-2.5/a
    litellm_params:
      model: anthropic/kimi-k2.5
      api_base: https://api.moonshot.ai/anthropic
      api_key: os.environ/MOONSHOT_API_KEY

  # backup
  - model_name: opencode-go/glm-5.1
    litellm_params:
      model: openai/glm-5.1
      api_base: https://opencode.ai/zen/go/v1
      api_key: os.environ/OPENCODE_API_KEY

general_settings:
  database_url: os.environ/DATABASE_URL
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  num_retries: 1
  allowed_fails: 1
  cooldown_time: 3600

router_settings:
  model_group_alias:
    "code": "zai/glm-5.1"
    "code/a": "zai/glm-5.1/a"
    "pencil/a": "xiaomi/mimo-v2-omni/a"
  fallbacks:
    - code: ["moonshot/kimi-2.5"]
    - code/a: ["moonshot/kimi-2.5/a"]
    - pencil/a: ["moonshot/kimi-2.5/a"]
